// Resolves "<album>/<photoId>" references to URLs on the photo host.
// Manifests are generated by `pnpm photos add` / `pnpm import:strapi`.

export interface PhotoMeta {
  w: number;
  h: number;
  widths: number[];
  lqip: string;
  original: string;
}

export interface Photo extends PhotoMeta {
  src: string;
  url: (width: number, format?: 'avif' | 'webp') => string;
  srcset: (format: 'avif' | 'webp') => string;
  largest: string;
}

const manifests = import.meta.glob<Record<string, PhotoMeta>>('../data/photos/*.json', {
  eager: true,
  import: 'default',
});

// Local dev/preview serves public/photos; production points at the R2 bucket.
const BASE = (import.meta.env.PUBLIC_PHOTOS_URL ?? '/photos').replace(/\/$/, '');

export function getPhoto(src: string): Photo {
  const [album, id] = src.split('/');
  const meta = manifests[`../data/photos/${album}.json`]?.[id];
  if (!meta) {
    throw new Error(`Unknown photo "${src}". Is it in src/data/photos/${album}.json? (run \`pnpm photos add\`)`);
  }
  const url = (width: number, format: 'avif' | 'webp' = 'webp') => `${BASE}/${album}/${id}/${width}.${format}`;
  return {
    ...meta,
    src,
    url,
    srcset: (format) => meta.widths.map((w) => `${url(w, format)} ${w}w`).join(', '),
    largest: url(meta.widths.at(-1)!),
  };
}
