// Resolves "<album>/<photoId>" references to URLs on the photo host.
// Manifests are generated by `pnpm photos add` (scripts/lib/photos.mjs).

export interface PhotoMeta {
  w: number;
  h: number;
  widths: number[];
  lqip: string;
  original: string;
}

export interface Photo extends PhotoMeta {
  /** Canonical "<album>/<id>" reference. */
  src: string;
  album: string;
  id: string;
  /** The id without its content hash, e.g. "dscf-1434". */
  name: string;
  url: (width: number, format?: 'avif' | 'webp') => string;
  srcset: (format: 'avif' | 'webp') => string;
  largest: string;
  /** JPEG for link previews (og:image), at most 1200px wide. */
  og: { url: string; width: number; height: number };
}

const manifests = import.meta.glob<Record<string, PhotoMeta>>('../data/photos/*.json', {
  eager: true,
  import: 'default',
});

// Local dev/preview serves public/photos; production points at the R2 bucket.
const BASE = (import.meta.env.PUBLIC_PHOTOS_URL ?? '/photos').replace(/\/$/, '');
/** Where the photo files are served from (R2 in production, public/photos in dev). */
export const PHOTOS_BASE = BASE;

// Must match OG_WIDTH in scripts/lib/photos.mjs.
const OG_WIDTH = 1200;

/** Photo ids are "<file-name>-<8 hex hash>"; the name alone is enough to refer to them. */
export const photoName = (id: string) => id.replace(/-[0-9a-f]{8}$/, '');

/**
 * Look up a photo by "<album>/<id>". The id can be shortened to the file name
 * ("iceland/dscf-1434") as long as no other photo in that album shares it.
 */
export function getPhoto(src: string): Photo {
  const [album, ref] = src.split('/');
  const manifest = manifests[`../data/photos/${album}.json`] ?? {};
  let id = ref;
  if (!manifest[id]) {
    const matches = Object.keys(manifest).filter((key) => photoName(key) === ref);
    if (matches.length > 1) throw new Error(`Photo "${src}" is ambiguous (${matches.join(', ')}); use the full id.`);
    id = matches[0];
  }
  const meta = manifest[id];
  if (!meta) {
    throw new Error(`Unknown photo "${src}". Is it in src/data/photos/${album}.json? (run \`pnpm photos add\`)`);
  }
  const url = (width: number, format: 'avif' | 'webp' = 'webp') => `${BASE}/${album}/${id}/${width}.${format}`;
  const ogWidth = Math.min(OG_WIDTH, meta.w);
  return {
    ...meta,
    src: `${album}/${id}`,
    album,
    id,
    name: photoName(id),
    url,
    srcset: (format) => meta.widths.map((w) => `${url(w, format)} ${w}w`).join(', '),
    largest: url(meta.widths.at(-1)!),
    og: { url: `${BASE}/${album}/${id}/og.jpg`, width: ogWidth, height: Math.round((meta.h * ogWidth) / meta.w) },
  };
}
